"""sample table

Revision ID: bb6e8989dc75
Revises: df16ddadc351
Create Date: 2017-01-20 13:42:45.206330

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bb6e8989dc75'
down_revision = 'df16ddadc351'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp_table',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temp_table')
    # ### end Alembic commands ###
